import type { Metadata } from "next";
import { headers } from "next/headers";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import parser from "ua-parser-js";

import { ModalRoot } from "@/shared/layouts/Modal/ModalRoot";
import { authOptions } from "@/server/auth";
import Providers from "./providers";

import "../styles/globals.css";

const inter = Inter({
	variable: "--font-inter",
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);
	const headersList = await headers();
  const userAgent = headersList.get("user-agent") || "";
  const deviceType = parser(userAgent).device.type || "desktop";
	

	return (
		<html lang="en">
			<body
				className={`${inter.variable} antialiased`}
			>
				<Providers session={session} deviceType={deviceType}>
					<ModalRoot />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
