import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import parser from "ua-parser-js";

import { DeviceTypeProvider } from "@/providers/DeviceTypeProvider";
import { ModalRoot } from "@/shared/layouts/Modal/ModalRoot";
import { TRPCProvider } from "@/providers/TRPCProvider";

import "../styles/globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const headersList = await headers();

	const userAgent = headersList.get("user-agent") || "";

	const deviceType = parser(userAgent).device.type || "desktop";

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<TRPCProvider>
					<DeviceTypeProvider deviceType={deviceType}>
						<ModalRoot />
						<main>{children}</main>
					</DeviceTypeProvider>
				</TRPCProvider>
			</body>
		</html>
	);
}
